// js/products.js - Central database for your SimSim Fun Store
const SIMSIM_PRODUCTS = [
    {
        id: "prod-1",
        title: "The Time-Travel School Bus",
        type: "book",
        category: "Bedtime Stories-Book",
        ageGroup: "Ages 3-6",
        price: 3.00,
        images: [
            "images/time/The Time-Travel School Bus.jpg",
            "images/time/the_city.jpg",
            "images/time/egypt.jpg",
            "images/time/dinosour.jpg",
        ],
        description: "Takes young readers on an unforgettable adventure through history, science, and space! When Emma, Leo, Mia, and Ben climb aboard the magical talking bus, Buzzy, they travel to the age of dinosaurs, explore the pyramids of Ancient Egypt, visit a medieval castle, journey across the Solar System, and even discover a city of the future. Along the way, they meet friendly guides, solve exciting puzzles, and learn fascinating facts about history, geography, teamwork, and science.",
        downloadUrl: "assets/pdfs/The Time-Travel School Bus.pdf",
        videoUrl: ""
    },
    {
        id: "prod-2",
        title: "Fire Truck Freddie's Hero Adventure",
        type: "coloring-activity",
        category: "Activities-Coloring Book",
        ageGroup: "Ages 5-7",
        price: 4.85,
        images: [
            "images/fire/fire_truck.jpg",
            "images/fire/firetruck1.png",
            "images/fire/firetruck2.png",
            "images/fire/firetruck3.png",
        ],
        description: "Fire Truck Freddie on 40 exciting comic-style adventures filled with laughter, learning, and heroic rescues! Alongside Captain Bella and their friends, Freddie helps animals, teaches important fire safety rules, explores colorful shapes, discovers bright colors, and shows how teamwork makes every mission a success.",
        downloadUrl: "assets/pdfs/Fire Truck Freddie's Hero Adventure.pdf",
        videoUrl: ""
    },
    {
        id: "prod-3",
        title: "Jojo the little bee",
        type: "video",
        category: "Bedtime Stories-video",
        ageGroup: "Ages 4-7",
        price: 5.00,
        images: [
            "images/jojo/Jojo the little bee.jpg",
            "images/jojo/Jojo the little bee1.jpg",
            "images/jojo/Jojo the little bee2.jpg",
            "images/jojo/Jojo the little bee3.jpg",
        ],
        description: "Little Jojo the bee lives with her loving family deep inside a giant tree in the forest. One sunny morning, she wakes up, exercises her tiny wings, and flies out wearing her colorful dress to collect sweet flower nectar for breakfast.",
        downloadUrl: "#",
        videoUrl: "assets/videos/jojo bee.mp4"
    },
    {
        id: "prod-4",
        title: "Bobo The Panda",
        type: "book",
        category: "Bedtime Stories-Book",
        ageGroup: "Ages 4-7",
        price: 4.85,
        images: [
            "images/bobo/Bobothepanda.jpg",
            "images/bobo/Bobothepanda1.jpg",
            "images/bobo/Bobothepanda2.jpg",
            "images/bobo/Bobothepanda3.jpg",
        ],
        description: "Bobo the Panda on a heartwarming forest adventure filled with friendship, teamwork, and fun! Every day, Bobo enjoys time with his loving family, playful friends, and wonderful school.",
        downloadUrl: "assets/pdfs/Bobo The Panda.pdf",
        videoUrl: ""
    },
    {
        id: "prod-5",
        title: "My Comic Coloring Book",
        type: "coloring-activity",
        category: "Comic Coloring Book",
        ageGroup: "Ages 4-8",
        price: 4.85,
        images: [
            "images/mcomic/My Comic Coloring Book.jpg",
            "images/mcomic/My Comic Coloring Book1.png",
            "images/mcomic/My Comic Coloring Book2.png",
            "images/mcomic/My Comic Coloring Book3.png",
        ],
        description: "Engage young learners with a vibrant collection of coloring pages and fun educational activities. This book helps children practice essential skills while expressing their creativity.",
        downloadUrl: "assets/pdfs/My Comic Coloring Book.pdf",
        videoUrl: ""
    },
    {
        id: "prod-6",
        title: "Detective Dino",
        type: "coloring-activity",
        category: "Comic Coloring Book",
        ageGroup: "Ages 5-8",
        price: 4.85,
        images: [
            "images/dino/Detective Dino.jpg",
            "images/dino/Detective Dino1.png",
            "images/dino/Detective Dino2.png",
            "images/dino/Detective Dino3.png",
        ],
        description: "Alphabet Valley is bright and colorful again. The Alphabet Crystals sparkle safely inside the museum, and every letter shines across books, signs, songs, and classrooms. Detective Dino smiles proudly as all the animal friends celebrate together with balloons, confetti, and music. Children review the alphabet one last time while everyone cheers. Detective Dino reminds everyone that every letter helps us read, speak, write, and learn new words. The adventure ends with laughter, friendship.",
        downloadUrl: "assets/pdfs/Detective Dino.pdf",
        videoUrl: ""
    },
    {
        id: "prod-7",
        title: "Benny The Bear",
        type: "coloring-activity",
        category: "Comic Coloring Book",
        ageGroup: "Ages 4-8",
        price: 4.85,
        images: [
            "images/bbear/Benny Bear.jpg",
            "images/bbear/Benny Bear1.jpg",
            "images/bbear/Benny Bear2.jpg",
            "images/bbear/Benny Bear3.jpg",
        ],
        description: "Is a fun-filled comic-style coloring book that helps children ages 5–7 build English skills through exciting stories, colorful adventures, and interactive learning.",
        downloadUrl: "assets/pdfs/Benny The Bear.pdf",
        videoUrl: ""
    },
    {
        id: "prod-8",
        title: "Happy Farm Animals",
        type: "coloring-activity",
        category: "Comic Coloring Book",
        ageGroup: "Ages 4-8",
        price: 4.85,
        images: [
            "images/farm/Happy Farm.jpg",
            "images/farm/Happy Farm1.png",
            "images/farm/Happy Farm2.png",
            "images/farm/Happy Farm3.png",
        ],
        description: "Welcome to Sunny Farm, where cheerful animals are getting ready for the biggest Talent Show ever! Join Clara the Cow, Percy the Pig, Holly the Horse, Daisy the Sheep, Rocky the Rooster, and their friends as they discover colors, shapes, numbers, healthy foods, teamwork, and kindness through funny adventures. ",
        downloadUrl: "assets/pdfs/Happy Farm Animals.pdf",
        videoUrl: ""
    },
     {
        id: "prod-9",
        title: "Super Bear",
        type: "video",
        category: "Bedtime Stories-video",
        ageGroup: "Ages 4-7",
        price: 5.00,
        images: [
            "images/Super/Super .jpg",
            "images/Super/Super1.jpg",
            "images/Super/Super2.jpg",
            "images/Super/Super3.jpg",
        ],
        description: "ZeeZo, a cheerful little bear who loves adventures, family, and exploring the forest. One day, he discovers a magical glowing Star Crystal that gives him amazing powers, including flying and super strength. Excited by his new abilities, ZeeZo learns that being a true hero is not about showing off, but about helping others with kindness and responsibility. ",
        downloadUrl: "#",
        videoUrl: "https://canva.link/jbboq013w9dliwf"
    },
    {
        id: "puzzle-time-bus",
        title: "Time-Travel Bus Puzzle",
        type: "puzzle",
        category: "Puzzle Game",
        ageGroup: "Ages 3-8",
        price: 0,
        images: ["images/time/The Time-Travel School Bus.jpg"],
        description: "Put the magical school bus back together and get ready for the next adventure.",
        downloadUrl: "#",
        videoUrl: ""
    },
    {
        id: "puzzle-super-bear",
        title: "Super Bear Puzzle",
        type: "puzzle",
        category: "Puzzle Game",
        ageGroup: "Ages 4-8",
        price: 0,
        images: ["images/Super/Super .jpg"],
        description: "Solve the Super Bear picture puzzle and help ZeeZo get ready to fly.",
        downloadUrl: "#",
        videoUrl: ""
    },
    {
        id: "puzzle-happy-farm",
        title: "Happy Farm Puzzle",
        type: "puzzle",
        category: "Puzzle Game",
        ageGroup: "Ages 4-8",
        price: 0,
        images: ["images/farm/Happy Farm.jpg"],
        description: "Join the farm friends by assembling their colorful picture.",
        downloadUrl: "#",
        videoUrl: ""
    },
    {
        id: "game-find-the-animal",
        title: "Find the Animal",
        type: "puzzle-game",
        category: "Puzzle Game",
        ageGroup: "Ages 4-8",
        price: 3.00,
        images: ["puzzle-game/games/find-the-animal/assets/mainpuzzle.png"],
        description: "Match all 25 animals to their correct spots.",
        downloadUrl: "puzzle-game/games/find-the-animal/index.html",
        videoUrl: ""
    },
    {
        id: "game-collect-the-image",
        title: "Collect the Image",
        type: "puzzle-game",
        category: "Puzzle Game",
        ageGroup: "Ages 4-8",
        price: 3.00,
        images: ["puzzle-game/games/collect-the-image/assets/front.png"],
        description: "Drag and arrange pieces to complete the full picture.",
        downloadUrl: "puzzle-game/games/collect-the-image/index.html",
        videoUrl: ""
    },
    {
        id: "game-count-the-animals",
        title: "Count the Animals",
        type: "puzzle-game",
        category: "Puzzle Game",
        ageGroup: "Ages 4-8",
        price: 3.50,
        images: ["puzzle-game/games/counting-game/images/count the animals.png"],
        description: "Choose an animal and count the correct number of friends.",
        downloadUrl: "puzzle-game/games/counting-game/index.html",
        videoUrl: ""
    }
];