create table if not exists public.library_items (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    product_id text not null,
    product_data jsonb not null,
    purchased_at timestamptz not null default now(),
    unique (user_id, product_id)
);

alter table public.library_items enable row level security;

create policy "Users can read their own library"
    on public.library_items for select
    using (auth.uid() = user_id);

create policy "Users can add to their own library"
    on public.library_items for insert
    with check (auth.uid() = user_id);

create table if not exists public.purchases (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    product_id text not null,
    product_data jsonb not null,
    paypal_transaction_id text,
    payment_status text not null default 'completed',
    purchased_at timestamptz not null default now()
);

alter table public.purchases enable row level security;

create policy "Users can read their own purchases"
    on public.purchases for select
    using (auth.uid() = user_id);

create policy "Users can add their own purchases"
    on public.purchases for insert
    with check (auth.uid() = user_id);
