name = "simsimfunstore"
compatibility_date = "2026-08-23"
pages_build_output_dir = "public"

[vars]
PAYPAL_API_BASE = "https://api-m.sandbox.paypal.com"
SUPABASE_URL = "https://vcsfpaemlxofgbtuksct.supabase.co"

[[d1_databases]]
binding = "DB"
database_name = "my-db-simsimfunstore"
database_id = "e8c9758e-4f36-4b20-bc32-5f025eae5b74"
